// eslint-disable-next-line @nx/enforce-module-boundaries
import "../../../../libs/tailwind/global.css";
import Providers from "@/features/providers";
import { Toaster } from "@email-scheduler/ui";

export const metadata = {
  title: "Welcome to email-scheduler-fe",
  description: "Generated by create-nx-workspace",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          {children}
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
