// eslint-disable-next-line @nx/enforce-module-boundaries
import "../../../../libs/tailwind/global.css";

export const metadata = {
  title: "Welcome to email-scheduler-fe",
  description: "Generated by create-nx-workspace",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="p-6">{children}</body>
    </html>
  );
}
